### ISSUE TITLE
It isn't clear how to run tests

### ISSUE THREAD

**Issue by yurivict** [llnl/Elemental#156]
With ```-DHydrogen_ENABLE_TESTING=ON``` test executables are built, but it isn't clear how to run them.

Is there a build target that runs tests and displays their run summary?

**Comment by benson31** [comment]
`ninja test` or `ctest` will run them, though not necessarily in a meaningful way. If CMake cannot determine `MPIEXEC` for your system, it will not run the 4-rank MPI-enabled versions of the tests. When run this way, the tests are run with the default parameters.

The CMake flag may not be the best; it's really there so we can disable building the binaries at all and not waste flops building binaries that aren't installed when doing larger builds of LBANN.

**Comment by yurivict** [comment]
Thank you.

The tests run fine now.
