### ISSUE TITLE
Is there any relevant documentation available?

### ISSUE THREAD

**Issue by wanghongyu2001** [llnl/Elemental#176]
Is there any relevant documentation available? I couldn't find it on the Hydrogen README, and many pages of Elemental's documentation are inaccessible. I want to update an outdated dependency on the Elemental project to make it compatible with the latest Hydrogen. Can you help me with this?

**Comment by ndryden** [comment]
We don't host a version of the documentation, although you can likely build it yourself should you want to.

Note, however, that Hydrogen is _not_ a full replacement for Elemental: We have removed significant functionality and do not maintain some portions of what remains. If what you need is distributed matrices and BLAS routines, you should be fine (and please report any issues with them), but if you need more advanced features (e.g., most solvers), we don't support those.
