### ISSUE TITLE
libelemental.org dead?

### ISSUE THREAD

**Issue by mgates3** [llnl/Elemental#180]
The link on the main page (https://github.com/LLNL/Elemental) to libelemental.org goes to an empty website that says "Nothing found" in German.

**Comment by ndryden** [comment]
We (those behind this fork) have never controlled libelemental.org, which was maintained by Elemental's original maintainers (Jack Poulson et al.). I think we just never removed the link from when we forked it. We can do that to eliminate confusion.

(cc @benson31 )

**Comment by benson31** [comment]
See elemental/elemental#276 and elemental/elemental#278. I don't have admin on this space (@bvanessen) but we can work on removing/changing that.

**Comment by benson31** [comment]
Ok, I think this is taken care of. Please reopen if I've missed something.
