### ISSUE TITLE
cudaDeviceSynchronize within EL_CHECK_MPI

### ISSUE THREAD

**Issue by naoyam** [llnl/Elemental#41]
Is this cudaDeviceSynchronize necessary?

https://github.com/LLNL/Elemental/blob/220e70cbda5bbfe228179e463b9b8d71256f2ff2/src/core/imports/mpi_utils.hpp#L27

It seems it gets called every time EL_CHECK_MPI is used no matter it's debug build or not. We've seen extraordinary longer latency with cudaDeviceSynchronize, so for performance reasons we do not want it in performance critical paths.

This may be a correctness problem too. For example, a data exchange between a pair of MPI ranks:
```
EL_CHECK_MPI(MPI_Irecv to device-memory from rank X);
EL_CHECK_MPI(MPI_Isend of device-memory to rank X);
EL_CHECK_MPI(MPI_Waitall(...));
```
should work. However, the cudaDeviceSynchronize after MPI_Irecv may not return if MPI_Irecv uses a persistent CUDA kernel that runs until the irecv is completed.

**Comment by benson31** [comment]
I don't think it's necessary. I understand your possible correctness issue. I am in favor of removing this sync. If something bad happens, we can think a bit harder about the correct fix.

I'm working on improving sync semantics in hydrogen. Hopefully that will help, too.
