### ISSUE TITLE
What is the status of this project and what are its goals?

### ISSUE THREAD

**Issue by goxberry** [llnl/Elemental#60]
The `tl;dr` version: what is the status of this project and what are its goals? To the best of my knowledge, Jack no longer actively maintains the root Elemental repo, aside from the occasional PR merge. At first glance, the README for this project looks essentially identical to that of the root Elemental repo, but there are clearly new features added to this fork, like support for the [Aluminum GPU communication library](https://github.com/LLNL/Aluminum). Is the intention to continue to maintain this Elemental fork as long as LBANN is maintained?

The LLNL reduced order modeling library [libROM](https://github.com/LLNL/libROM) is interested in using this fork of Elemental for its distributed memory version of QR factorization with column pivoting (QRCP), but we'd like to have some idea as to whether this fork will be maintained for the foreseeable future before we invest effort in using it.

**Comment by poulson** [comment]
If someone wants to actually fund me to maintain some of Elemental, I would contribute time to it, but I don't own a supercomputer and spend my volunteering energy on other things now.

**Comment by bvanessen** [comment]
The LLNL LBANN team is maintaining a fork of Elemental that we use for large scale deep learning.  We have extended it for GPU allocation and computation, but have also simplified the subset of the library that we are supporting.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470
