### ISSUE TITLE
CMake build fails because of "Unknown option 'pthread'"

### ISSUE THREAD

**Issue by mxmlnkn** [llnl/Elemental#69]
I already reported this at [CMake](https://gitlab.kitware.com/cmake/cmake/issues/18897)
I noticed that [Aluminum](https://github.com/LLNL/Aluminum) v0.1 has the same problem.
Am I doing something wrong? I can't see this behavior documented anywhere. Can a fix be implemented inside the CMakeLists.txt for this? "How is Elemental supposed to be built with CMake?".  I think, I tried already CMake 3.10, 3.13, and 3.14. All of them have this problem.

Build steps and error:

    apt-get -y install libopenblas-dev libopenmpi-dev cmake
    wget -qO- https://github.com/LLNL/Elemental/archive/v1.0.1.tar.gz | tar -xz && cd Elemental-* && mkdir build && cd $_
    export CUB_DIR=$( find /usr/local/ -name 'cub.cuh' | sed 's|/cub/cub\.cuh||' )
    cmake -DHydrogen_USE_64BIT_INTS=ON -DHydrogen_ENABLE_OPENMP=ON -DBUILD_SHARED_LIBS=ON -DHydrogen_ENABLE_ALUMINUM=ON -DHydrogen_ENABLE_CUDA=ON ..
        fatal: not a git repository (or any of the parent directories): .git
        -- Found CUB: /usr/local/cuda-10.0/targets/x86_64-linux/include/thrust/system/cuda/detail
        -- Found OpenMP_CXX: -fopenmp
        -- Aluminum support enabled.
        -- Aluminum detected with NCCL2 backend support.
        -- Aluminum detected with MPI-CUDA backend support.
        -- Using __restrict__ keyword.
        -- Found OpenMP_CXX: -fopenmp
        -- A library with BLAS API found.
        -- A library with LAPACK API found.
        -- Found LAPACK: /usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so
        -- Using BLAS with trailing underscore.
        -- Using LAPACK with trailing underscore.
        BUILD SHARED
        -- Configuring done
        -- Generating done
        -- Build files have been written to: /opt/Elemental-1.0.1/build

    make -j 4 install
        Scanning dependencies of target Hydrogen
        [  0%] Building CUDA object CMakeFiles/Hydrogen.dir/src/blas_like/level1/GPU/Axpy.cu.o
        nvcc fatal   : Unknown option 'pthread'
        CMakeFiles/Hydrogen.dir/build.make:62: recipe for target 'CMakeFiles/Hydrogen.dir/src/blas_like/level1/GPU/Axpy.cu.o' failed
        make[2]: *** [CMakeFiles/Hydrogen.dir/src/blas_like/level1/GPU/Axpy.cu.o] Error 1
        CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Hydrogen.dir/all' failed
        make[1]: *** [CMakeFiles/Hydrogen.dir/all] Error 2
        Makefile:140: recipe for target 'all' failed
        make: *** [all] Error 2

Workaround:

    cmake <...>
    find . -type f | xargs -I{} bash -c 'if grep -q "nvcc.* -pthread" "$0"; then sed -i -r "/nvcc.* -pthread/{s: -pthread( |$): :g}" "$0"; fi' {}
    make -j 4 install

**Comment by benson31** [comment]
This is a known issue; the proper fix is rather involved and in progress.

It's not CMake's fault, per se (that said, I don't think they handle device linking very well). The idea is to separate out the dlinked compilation units into language-specific libraries. It's not clear how straight-forward this actually is because MPI and CUDA get tied together fairly tightly in our codes.

**Comment by mxmlnkn** [comment]
So, how do you internally compile it currently? I'm doing a search&delete approach but is that really how you also do it?:

```bash
cmake ..
find . -type f | xargs -I{} bash -c '
    if grep -q -E "(nvcc|CUDA_FLAG).* -pthread" "$0"; then
        sed -i -r "/nvcc.* -pthread/{s: -pthread( |$): :g}" "$0";
    fi' {}
make -j $( nproch )
```

Btw, I have the same problem with Aluminum and LBANN.

**Comment by benson31** [comment]
Our MPI libraries do not require pthread linkage. I can patch this inside the CMake for you.
