### ISSUE TITLE
Documentation for elemental

### ISSUE THREAD

**Issue by vadithya1989** [llnl/Elemental#80]
Hi,

I was wondering if you had the PDF documentation of elemental. 

Thanks

**Comment by benson31** [comment]
We do not, sorry.

**Comment by poulson** [comment]
The source is here: https://github.com/elemental/elemental-web

**Comment by andreasnoack** [comment]
@benson31 Any chance that you could build and host the documentation that Jack links to? Your colleagues out west are using Elemental, https://github.com/JuliaParallel/Elemental.jl/issues/72#issuecomment-937148163,  but are having a hard time because the documentation is no longer available.
