### ISSUE TITLE
Compilation error with Intel 2019.5

### ISSUE THREAD

**Issue by jonas-phys** [llnl/Elemental#88]
Compilation fails at the file Instantiate.cpp because of creation of purely virtual object. 
CMake options used:

cmake .. -GNinja -D -MATH_LIBS="-L/opt/intel/mkl/lib/intel64 -mkl" -D CMAKE_CXX_COMPILER=/opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/icpc -D CMAKE_C_COMPILER=/opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/icc -D CMAKE_Fortran_COMPILER=/opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/ifort -D HYDROGEN_HAVE_MKL=ON

Complete error message: 
`
FAILED: CMakeFiles/Hydrogen_CXX.dir/src/core/Instantiate.cpp.o 
/opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64/icpc   -I../include -I../include/El -Iinclude -isystem /opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/include -fPIC   -Wall -Wextra -Wno-unused-parameter -pedantic -std=gnu++14 -MD -MT CMakeFiles/Hydrogen_CXX.dir/src/core/Instantiate.cpp.o -MF CMakeFiles/Hydrogen_CXX.dir/src/core/Instantiate.cpp.o.d -o CMakeFiles/Hydrogen_CXX.dir/src/core/Instantiate.cpp.o -c ../src/core/Instantiate.cpp
../include/El/core/Matrix/impl_cpu.hpp(79): error: object of abstract class type "El::AbstractMatrix<uint8_t={__uint8_t={unsigned char}}>" is not allowed:
            function "El::AbstractMatrix<T>::Copy [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::Construct [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemorySize [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::GetDevice [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemoryMode [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::SetMemoryMode [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer() [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer() const [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) const [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::CRef [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) const [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::Ref [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_get_ [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_set_ [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_empty_ [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_resize_ [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_swap_ [with T=uint8_t={__uint8_t={unsigned char}}]" is a pure virtual function
      : AbstractMatrix<T>{std::move(A)},
                          ^
          detected during instantiation of "El::Matrix<T, hydrogen::Device::CPU>::Matrix(El::Matrix<T, hydrogen::Device::CPU> &&) [with T=uint8_t={__uint8_t={unsigned char}}]" at line 698

../include/El/core/Matrix/impl_cpu.hpp(79): error: object of abstract class type "El::AbstractMatrix<El::Int={int}>" is not allowed:
            function "El::AbstractMatrix<T>::Copy [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::Construct [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemorySize [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::GetDevice [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemoryMode [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::SetMemoryMode [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer() [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer() const [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) const [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::CRef [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) const [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::Ref [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_get_ [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_set_ [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_empty_ [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_resize_ [with T=El::Int={int}]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_swap_ [with T=El::Int={int}]" is a pure virtual function
      : AbstractMatrix<T>{std::move(A)},
                          ^
          detected during instantiation of "El::Matrix<T, hydrogen::Device::CPU>::Matrix(El::Matrix<T, hydrogen::Device::CPU> &&) [with T=El::Int={int}]" at line 114 of "../include/El/macros/Instantiate.h"

../include/El/core/Matrix/impl_cpu.hpp(79): error: object of abstract class type "El::AbstractMatrix<float>" is not allowed:
            function "El::AbstractMatrix<T>::Copy [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::Construct [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemorySize [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::GetDevice [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemoryMode [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::SetMemoryMode [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer() [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer() const [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) const [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::CRef [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) const [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::Ref [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_get_ [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_set_ [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_empty_ [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_resize_ [with T=float]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_swap_ [with T=float]" is a pure virtual function
      : AbstractMatrix<T>{std::move(A)},
                          ^
          detected during instantiation of "El::Matrix<T, hydrogen::Device::CPU>::Matrix(El::Matrix<T, hydrogen::Device::CPU> &&) [with T=float]" at line 122 of "../include/El/macros/Instantiate.h"

../include/El/core/Matrix/impl_cpu.hpp(79): error: object of abstract class type "El::AbstractMatrix<double>" is not allowed:
            function "El::AbstractMatrix<T>::Copy [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::Construct [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemorySize [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::GetDevice [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemoryMode [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::SetMemoryMode [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer() [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer() const [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) const [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::CRef [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) const [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::Ref [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_get_ [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_set_ [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_empty_ [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_resize_ [with T=double]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_swap_ [with T=double]" is a pure virtual function
      : AbstractMatrix<T>{std::move(A)},
                          ^
          detected during instantiation of "El::Matrix<T, hydrogen::Device::CPU>::Matrix(El::Matrix<T, hydrogen::Device::CPU> &&) [with T=double]" at line 125 of "../include/El/macros/Instantiate.h"

../include/El/core/Matrix/impl_cpu.hpp(79): error: object of abstract class type "El::AbstractMatrix<El::Complex<float>>" is not allowed:
            function "El::AbstractMatrix<T>::Copy [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::Construct [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemorySize [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::GetDevice [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemoryMode [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::SetMemoryMode [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer() [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer() const [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) const [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::CRef [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) const [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::Ref [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_get_ [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_set_ [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_empty_ [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_resize_ [with T=El::Complex<float>]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_swap_ [with T=El::Complex<float>]" is a pure virtual function
      : AbstractMatrix<T>{std::move(A)},
                          ^
          detected during instantiation of "El::Matrix<T, hydrogen::Device::CPU>::Matrix(El::Matrix<T, hydrogen::Device::CPU> &&) [with T=El::Complex<float>]" at line 146 of "../include/El/macros/Instantiate.h"

../include/El/core/Matrix/impl_cpu.hpp(79): error: object of abstract class type "El::AbstractMatrix<El::Complex<double>>" is not allowed:
            function "El::AbstractMatrix<T>::Copy [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::Construct [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemorySize [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::GetDevice [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::MemoryMode [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::SetMemoryMode [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer() [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::Buffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer() const [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::LockedBuffer(El::AbstractMatrix<T>::index_type={El::Int={int}}, El::AbstractMatrix<T>::index_type={El::Int={int}}) const [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::CRef [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) const [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::Ref [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::operator()(El::Int={int}, El::Int={int}) [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_get_ [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_set_ [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_empty_ [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_resize_ [with T=El::Complex<double>]" is a pure virtual function
            function "El::AbstractMatrix<T>::do_swap_ [with T=El::Complex<double>]" is a pure virtual function
      : AbstractMatrix<T>{std::move(A)},
`
Is there a obvious fix I'm missing?

**Comment by benson31** [comment]
Apparently Intel doesn't like the curly-braced initialization. I've fixed this and will push as soon as I verify there are no other issues.

Note: This is *not* Elemental -- there is no C or Fortran code, so you don't need those CMake arguments, and we no longer support `MATH_LIBS` like Elemental does. The [CMake FindLapack.cmake](https://cmake.org/cmake/help/v3.14/module/FindLAPACK.html) does a reasonable job finding MKL with just `-DBLA_VENDOR=Intel10_64lp` (assuming the rest of the environment is setup correctly, e.g., with `MKLROOT` set to the right path). See the CMake documentation for other MKL configurations to find the one that fits your needs.

The CMake line I've been using is:
```
cmake -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=YES \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      -DCMAKE_CXX_COMPILER=$(which icpc) \
      -DBLA_VENDOR=Intel10_64lp \
      ..
```
