### ISSUE TITLE
Dense linear solve with GPUs

### ISSUE THREAD

**Issue by vqd8a** [llnl/Elemental#97]
I am new to Elemental and I would like to ask whether El::LinearSolve can support GPUs or is it just running on CPUs? Thank you. Vinh Dang

**Comment by benson31** [comment]
In this fork, it probably doesn't run at all. This fork is only maintained to the level required by our deep learning toolkit, so the operations are limited to basic utilities and BLAS-like capability. Thus, we have not ported a dense linear solve to run with GPUs at this time.

**Comment by vqd8a** [comment]
Thanks, @benson31 .
